version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: strict
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/kolo/xmlrpc
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        text: 'Magic number: [0-9]{1},'
      - linters:
          - mnd
        text: 'Magic number: 0[0-7]{3},'
      - linters:
          - mnd
        text: 'Magic number: 255,'
      - linters:
          - mnd
        text: 'Magic number: 32,'
      - linters:
          - mnd
        text: 'Magic number: 10,'
      - linters:
          - lll
        path: _test\.go
      - linters:
          - gocritic
        text: appendAssign
      - linters:
          - gochecknoinits
        path: .*/cmd/.*\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
