// Code generated by MockGen. DO NOT EDIT.
// Source: rtorrent.go
//
// Generated by this command:
//
//	mockgen -source=rtorrent.go -destination=rtorrent_moq.go -package=rtorrent -typed
//

// Package rtorrent is a generated GoMock package.
package rtorrent

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *MockClientCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
	return &MockClientCloseCall{Call: call}
}

// MockClientCloseCall wrap *gomock.Call
type MockClientCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCloseCall) Return(arg0 error) *MockClientCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCloseCall) Do(f func() error) *MockClientCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCloseCall) DoAndReturn(f func() error) *MockClientCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DownloadRate mocks base method.
func (m *MockClient) DownloadRate() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadRate")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadRate indicates an expected call of DownloadRate.
func (mr *MockClientMockRecorder) DownloadRate() *MockClientDownloadRateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadRate", reflect.TypeOf((*MockClient)(nil).DownloadRate))
	return &MockClientDownloadRateCall{Call: call}
}

// MockClientDownloadRateCall wrap *gomock.Call
type MockClientDownloadRateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDownloadRateCall) Return(arg0 int, arg1 error) *MockClientDownloadRateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDownloadRateCall) Do(f func() (int, error)) *MockClientDownloadRateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDownloadRateCall) DoAndReturn(f func() (int, error)) *MockClientDownloadRateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DownloadTotal mocks base method.
func (m *MockClient) DownloadTotal() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadTotal")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadTotal indicates an expected call of DownloadTotal.
func (mr *MockClientMockRecorder) DownloadTotal() *MockClientDownloadTotalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadTotal", reflect.TypeOf((*MockClient)(nil).DownloadTotal))
	return &MockClientDownloadTotalCall{Call: call}
}

// MockClientDownloadTotalCall wrap *gomock.Call
type MockClientDownloadTotalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDownloadTotalCall) Return(arg0 int, arg1 error) *MockClientDownloadTotalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDownloadTotalCall) Do(f func() (int, error)) *MockClientDownloadTotalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDownloadTotalCall) DoAndReturn(f func() (int, error)) *MockClientDownloadTotalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UploadRate mocks base method.
func (m *MockClient) UploadRate() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadRate")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadRate indicates an expected call of UploadRate.
func (mr *MockClientMockRecorder) UploadRate() *MockClientUploadRateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadRate", reflect.TypeOf((*MockClient)(nil).UploadRate))
	return &MockClientUploadRateCall{Call: call}
}

// MockClientUploadRateCall wrap *gomock.Call
type MockClientUploadRateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUploadRateCall) Return(arg0 int, arg1 error) *MockClientUploadRateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUploadRateCall) Do(f func() (int, error)) *MockClientUploadRateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUploadRateCall) DoAndReturn(f func() (int, error)) *MockClientUploadRateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UploadTotal mocks base method.
func (m *MockClient) UploadTotal() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTotal")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadTotal indicates an expected call of UploadTotal.
func (mr *MockClientMockRecorder) UploadTotal() *MockClientUploadTotalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTotal", reflect.TypeOf((*MockClient)(nil).UploadTotal))
	return &MockClientUploadTotalCall{Call: call}
}

// MockClientUploadTotalCall wrap *gomock.Call
type MockClientUploadTotalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUploadTotalCall) Return(arg0 int, arg1 error) *MockClientUploadTotalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUploadTotalCall) Do(f func() (int, error)) *MockClientUploadTotalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUploadTotalCall) DoAndReturn(f func() (int, error)) *MockClientUploadTotalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// getInt mocks base method.
func (m *MockClient) getInt(method, arg string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getInt", method, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getInt indicates an expected call of getInt.
func (mr *MockClientMockRecorder) getInt(method, arg any) *MockClientgetIntCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getInt", reflect.TypeOf((*MockClient)(nil).getInt), method, arg)
	return &MockClientgetIntCall{Call: call}
}

// MockClientgetIntCall wrap *gomock.Call
type MockClientgetIntCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientgetIntCall) Return(arg0 int, arg1 error) *MockClientgetIntCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientgetIntCall) Do(f func(string, string) (int, error)) *MockClientgetIntCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientgetIntCall) DoAndReturn(f func(string, string) (int, error)) *MockClientgetIntCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// getSliceSlice mocks base method.
func (m *MockClient) getSliceSlice(method string, args ...string) ([][]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{method}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "getSliceSlice", varargs...)
	ret0, _ := ret[0].([][]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getSliceSlice indicates an expected call of getSliceSlice.
func (mr *MockClientMockRecorder) getSliceSlice(method any, args ...any) *MockClientgetSliceSliceCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{method}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getSliceSlice", reflect.TypeOf((*MockClient)(nil).getSliceSlice), varargs...)
	return &MockClientgetSliceSliceCall{Call: call}
}

// MockClientgetSliceSliceCall wrap *gomock.Call
type MockClientgetSliceSliceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientgetSliceSliceCall) Return(arg0 [][]any, arg1 error) *MockClientgetSliceSliceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientgetSliceSliceCall) Do(f func(string, ...string) ([][]any, error)) *MockClientgetSliceSliceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientgetSliceSliceCall) DoAndReturn(f func(string, ...string) ([][]any, error)) *MockClientgetSliceSliceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// getSliceSliceByHash mocks base method.
func (m *MockClient) getSliceSliceByHash(method string, args ...string) ([][]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{method}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "getSliceSliceByHash", varargs...)
	ret0, _ := ret[0].([][]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getSliceSliceByHash indicates an expected call of getSliceSliceByHash.
func (mr *MockClientMockRecorder) getSliceSliceByHash(method any, args ...any) *MockClientgetSliceSliceByHashCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{method}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getSliceSliceByHash", reflect.TypeOf((*MockClient)(nil).getSliceSliceByHash), varargs...)
	return &MockClientgetSliceSliceByHashCall{Call: call}
}

// MockClientgetSliceSliceByHashCall wrap *gomock.Call
type MockClientgetSliceSliceByHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientgetSliceSliceByHashCall) Return(arg0 [][]any, arg1 error) *MockClientgetSliceSliceByHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientgetSliceSliceByHashCall) Do(f func(string, ...string) ([][]any, error)) *MockClientgetSliceSliceByHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientgetSliceSliceByHashCall) DoAndReturn(f func(string, ...string) ([][]any, error)) *MockClientgetSliceSliceByHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// getString mocks base method.
func (m *MockClient) getString(method, arg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getString", method, arg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getString indicates an expected call of getString.
func (mr *MockClientMockRecorder) getString(method, arg any) *MockClientgetStringCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getString", reflect.TypeOf((*MockClient)(nil).getString), method, arg)
	return &MockClientgetStringCall{Call: call}
}

// MockClientgetStringCall wrap *gomock.Call
type MockClientgetStringCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientgetStringCall) Return(arg0 string, arg1 error) *MockClientgetStringCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientgetStringCall) Do(f func(string, string) (string, error)) *MockClientgetStringCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientgetStringCall) DoAndReturn(f func(string, string) (string, error)) *MockClientgetStringCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// getStringSlice mocks base method.
func (m *MockClient) getStringSlice(method string, args ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{method}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "getStringSlice", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getStringSlice indicates an expected call of getStringSlice.
func (mr *MockClientMockRecorder) getStringSlice(method any, args ...any) *MockClientgetStringSliceCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{method}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getStringSlice", reflect.TypeOf((*MockClient)(nil).getStringSlice), varargs...)
	return &MockClientgetStringSliceCall{Call: call}
}

// MockClientgetStringSliceCall wrap *gomock.Call
type MockClientgetStringSliceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientgetStringSliceCall) Return(arg0 []string, arg1 error) *MockClientgetStringSliceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientgetStringSliceCall) Do(f func(string, ...string) ([]string, error)) *MockClientgetStringSliceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientgetStringSliceCall) DoAndReturn(f func(string, ...string) ([]string, error)) *MockClientgetStringSliceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
